name: COVID19
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - pandas
  - geopandas
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - ipywidgets
    - mpl_toolkits
    - voila
