name: COVID19
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - pandas
  - pandas
  - geopandas
  - pip
  - pip:
    - matplotlib
    - ipywidgets
    - voila
    - pyarrow
    - descartes
    - GDAL
    - fiona
    - shapely